import './globals.css'
import { Inter, Nunito, Montserrat } from 'next/font/google'

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-header',
});

const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-subheader',
})
 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${montserrat.variable}`}>{children}</body>
    </html>
  )
}
